### ISSUE TITLE
VIEW 

### ISSUE THREAD

**Issue by krixstin** [krixstin/Exchange4Students#2]

**Comment by RedRoach51** [comment]
Need to implement a unique 'itemID' : 'string' attribute to all items to be able to differentiate between them. Not an issue to add to classes, but please make sure that any instances of creating/reading Items correctly reference and declare this attribute.

**Comment by krixstin** [comment]
helpful doc: https://stackoverflow.com/questions/53430860/how-to-get-data-and-display-in-html-from-firebase-using-angular-typescript/53431309
